#!/usr/bin/env python3
"""Brand the Anaconda installer ISO.

The installer environment is built by bootc-image-builder from Fedora packages,
not from our image, so nothing in system_files/ reaches it. Anaconda does,
however, load /run/install/product/anaconda-gtk.css at a higher priority than
its own stylesheet when that file exists. A kickstart %pre script runs before
the installer UI starts, so it can drop that file and its pixmaps in place.

This script renders the pixmaps (night sidebar, the Chief mark, night top bar)
and rewrites the %pre block in disk_config/iso.toml with them embedded as
base64. Run it after changing the mark or the palette:

    python scripts/gen-installer-branding.py
"""
import base64
import io
import re
import sys
from pathlib import Path

import numpy as np
from PIL import Image, ImageDraw, ImageFilter

sys.path.insert(0, str(Path(__file__).resolve().parent))
from pridwen_mark import CREAM, render_mark  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
TOML = ROOT / "disk_config" / "iso.toml"
OUT = ROOT / "disk_config" / "branding"

NIGHT = (17, 19, 24)
NIGHT_DEEP = (9, 10, 13)
BLOBS = [((44, 50, 78), 0.5, 0.18, 260), ((28, 44, 62), 0.6, 0.55, 220), ((52, 38, 62), 0.4, 0.9, 300)]


def sidebar_bg(w=192, h=1400):
    y = np.linspace(0, 1, h)[:, None, None]
    base = np.array(NIGHT, np.float32) * (1 - y) + np.array(NIGHT_DEEP, np.float32) * y
    out = np.broadcast_to(base, (h, w, 3)).astype(np.float32).copy()
    for colour, fx, fy, r in BLOBS:
        m = Image.new("L", (w, h), 0)
        cx, cy = fx * w, fy * h
        ImageDraw.Draw(m).ellipse((cx - r, cy - r, cx + r, cy + r), fill=255)
        m = m.filter(ImageFilter.GaussianBlur(90))
        a = np.asarray(m).astype(np.float32)[..., None] / 255.0 * 0.55
        out = out * (1 - a) + np.array(colour, np.float32) * a
    return Image.fromarray(np.clip(out, 0, 255).astype(np.uint8), "RGB")


def sidebar_logo(w=192, h=200):
    im = Image.new("RGBA", (w, h), (0, 0, 0, 0))
    mark = render_mark(104, CREAM)
    im.paste(mark, ((w - 104) // 2, 20), mark)
    return im


def topbar_bg():
    return Image.new("RGB", (4, 64), NIGHT)


CSS = """/* Pridwen OS installer look. Dropped in by the kickstart %pre; see scripts/gen-installer-branding.py. */
@define-color anaconda_bg_color #111318;
.logo-sidebar {
    background-image: url('/run/install/product/pixmaps/sidebar-bg.png');
    background-color: #111318;
    background-repeat: no-repeat;
    background-position: top left;
}
.logo {
    background-image: url('/run/install/product/pixmaps/sidebar-logo.png');
    background-color: transparent;
    background-repeat: no-repeat;
    background-position: 50% 0px;
}
.product-logo { background-image: none; }
AnacondaSpokeWindow #nav-box {
    background-color: #111318;
    background-image: none;
    color: #F2EDE3;
}
AnacondaSpokeWindow #nav-box label { color: #F2EDE3; }
"""


def b64(img, fmt="PNG"):
    buf = io.BytesIO()
    img.save(buf, fmt, optimize=True)
    return base64.b64encode(buf.getvalue()).decode()


def pre_block(files):
    lines = ["%pre --interpreter=/bin/bash",
             "# Pridwen installer branding (generated by scripts/gen-installer-branding.py).",
             "mkdir -p /run/install/product/pixmaps"]
    for name, data in files:
        lines.append(f"base64 -d > /run/install/product/{name} <<'B64'")
        for i in range(0, len(data), 76):
            lines.append(data[i:i + 76])
        lines.append("B64")
    lines.append("cat > /run/install/product/anaconda-gtk.css <<'CSS'")
    lines.append(CSS.rstrip())
    lines.append("CSS")
    lines.append("%end")
    return "\n".join(lines)


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    imgs = {"sidebar-bg.png": sidebar_bg(), "sidebar-logo.png": sidebar_logo(), "topbar-bg.png": topbar_bg()}
    files = []
    for name, im in imgs.items():
        im.save(OUT / name, optimize=True)
        files.append((f"pixmaps/{name}", b64(im)))
    (OUT / "anaconda-gtk.css").write_text(CSS, encoding="utf-8", newline="\n")

    toml = TOML.read_text(encoding="utf-8")
    new_pre = pre_block(files)
    if "%pre" in toml:
        toml = re.sub(r"%pre.*?%end", lambda _m: new_pre, toml, count=1, flags=re.S)
    else:
        toml = toml.replace('contents = """\n', 'contents = """\n' + new_pre + "\n", 1)
    TOML.write_text(toml, encoding="utf-8", newline="\n")
    size = sum(len(d) for _, d in files)
    print(f"wrote {len(files)} pixmaps + css to {OUT}; %pre in {TOML} carries {size/1024:.0f} KiB of base64")


if __name__ == "__main__":
    main()
