#!/usr/bin/env python3
"""The Pridwen mark ("Chief"): a heater shield with a chevron cut out of it.

Single source of truth for the geometry. Everything that draws the mark
(the hicolor icons, the Plymouth boot frames, the GDM logo) imports this so
the shield is identical everywhere. Coordinates are on a 128-unit grid.

Run directly to (re)write the SVG icons:
    python scripts/pridwen_mark.py
"""
from pathlib import Path

import numpy as np
from PIL import Image, ImageDraw

CREAM = (242, 237, 227)
NIGHT = (17, 19, 24)
NIGHT_BLOB = (44, 50, 78)

# Shield outline: cubic Bezier segments (start, c1, c2, end) on the 128 grid.
SHIELD_SEGMENTS = [
    ((64, 12), (82, 12), (98, 15.5), (108, 20)),
    ((108, 20), (108, 20), (108, 58), (108, 58)),          # straight edge
    ((108, 58), (108, 86), (90, 106), (64, 118)),
    ((64, 118), (38, 106), (20, 86), (20, 58)),
    ((20, 58), (20, 58), (20, 20), (20, 20)),               # straight edge
    ((20, 20), (30, 15.5), (46, 12), (64, 12)),
]
# Chevron cut out of the shield (a "chief" in heraldry sits at the top).
CHEVRON = [(64, 44), (36, 70), (36, 84), (64, 58), (92, 84), (92, 70)]

SVG_PATH = (
    "M64 12 C 82 12 98 15.5 108 20 V 58 C 108 86 90 106 64 118 "
    "C 38 106 20 86 20 58 V 20 C 30 15.5 46 12 64 12 Z "
    "M64 44 L 36 70 L 36 84 L 64 58 L 92 84 L 92 70 Z"
)


def shield_polygon(samples=32):
    """Flatten the Bezier outline into a polygon."""
    pts = []
    for p0, p1, p2, p3 in SHIELD_SEGMENTS:
        for i in range(samples):
            t = i / samples
            u = 1 - t
            x = u**3 * p0[0] + 3 * u**2 * t * p1[0] + 3 * u * t**2 * p2[0] + t**3 * p3[0]
            y = u**3 * p0[1] + 3 * u**2 * t * p1[1] + 3 * u * t**2 * p2[1] + t**3 * p3[1]
            pts.append((x, y))
    return pts


def render_mark(size, colour=CREAM, ss=4, box=128):
    """Rasterise the mark at `size` px (RGBA, transparent background)."""
    big = size * ss
    k = big / box
    mask = Image.new("L", (big, big), 0)
    d = ImageDraw.Draw(mask)
    d.polygon([(x * k, y * k) for x, y in shield_polygon()], fill=255)
    d.polygon([(x * k, y * k) for x, y in CHEVRON], fill=0)
    mask = mask.resize((size, size), Image.LANCZOS)
    rgba = np.zeros((size, size, 4), np.uint8)
    rgba[..., :3] = colour
    rgba[..., 3] = np.asarray(mask)
    return Image.fromarray(rgba, "RGBA")


def svg_symbolic():
    """Mark only, currentColor; for the top bar and any place that tints icons."""
    return f'''<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128" width="16" height="16">
  <path fill="currentColor" fill-rule="evenodd" d="{SVG_PATH}"/>
</svg>
'''


def svg_icon():
    """App icon: cream mark on a night tile, so it reads on both canvases."""
    return f'''<?xml version="1.0" encoding="UTF-8"?>
<!-- Pridwen OS mark ("Chief"). Generated by scripts/pridwen_mark.py; edit there. -->
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128" width="128" height="128">
  <defs>
    <linearGradient id="tile" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#2C324E"/>
      <stop offset="1" stop-color="#111318"/>
    </linearGradient>
    <linearGradient id="rim" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#FFFFFF" stop-opacity="0.28"/>
      <stop offset="1" stop-color="#FFFFFF" stop-opacity="0.10"/>
    </linearGradient>
  </defs>
  <rect x="4" y="4" width="120" height="120" rx="30" fill="url(#tile)"/>
  <rect x="4.5" y="4.5" width="119" height="119" rx="29.5" fill="none" stroke="url(#rim)"/>
  <g transform="translate(64 64) scale(0.68) translate(-64 -64)">
    <path fill="#F2EDE3" fill-rule="evenodd" d="{SVG_PATH}"/>
  </g>
</svg>
'''


def main():
    root = Path(__file__).resolve().parent.parent
    apps = root / "system_files/usr/share/icons/hicolor/scalable/apps"
    sym = root / "system_files/usr/share/icons/hicolor/symbolic/apps"
    apps.mkdir(parents=True, exist_ok=True)
    sym.mkdir(parents=True, exist_ok=True)
    (apps / "pridwen.svg").write_text(svg_icon(), encoding="utf-8", newline="\n")
    (sym / "pridwen-symbolic.svg").write_text(svg_symbolic(), encoding="utf-8", newline="\n")
    print(f"wrote {apps / 'pridwen.svg'} and {sym / 'pridwen-symbolic.svg'}")


if __name__ == "__main__":
    main()
